### ISSUE TITLE
AS A TRAVELLER I WANT TO RESERVE A ROOM

### ISSUE THREAD

**Issue by IcebearMAC** [IcebearMAC/GarageMVC_Database#1]
UI:
BUTTON TO BOOK ROOM
ROOM PRICE PER DAY
TOTAL PRICE

**Comment by Gommash** [comment]
???? Should A Customer be able to rent a room in a garage?

**Comment by IcebearMAC** [comment]
Why should a customer rent a Room in a Garage??

**Comment by Doldas** [comment]
A garage is only a hotel for vehicles not humans, but it can  be a feature in later times.
